### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 1000
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 1000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "d3905340268c43dfaee40f0cb84b69e9",
  "accountNumber": "1000000000",
  "amount": 1000
}

### get transaction
GET http://localhost:8080/transaction/d3905340268c43dfaee40f0cb84b69e9